import type { Infer } from "convex/values";
import type { vItemAttributes } from "./validators";

export type DemoWardrobeItem = {
  key: string;
  wardrobe: "men" | "women";
  imagePath: string;
  attributes: Infer<typeof vItemAttributes>;
};

export const DEMO_WARDROBE: readonly DemoWardrobeItem[] = [
  {
    key: "v2-men-blue-check-shirt",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/blue-check-shirt.webp",
    attributes: {
      name: "Blue check shirt",
      category: "top",
      subcategory: "shirt",
      colours: {
        primary: "blue",
        secondary: ["black", "white"],
        hex: ["#577b9e", "#242424"],
      },
      pattern: "check",
      material: "cotton",
      season: ["spring", "autumn"],
      formality: "smart-casual",
      description: "An adult men’s blue, black and white checked long-sleeve button-down shirt.",
    },
  },
  {
    key: "v2-men-blue-tropical-shirt",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/blue-tropical-shirt.webp",
    attributes: {
      name: "Blue tropical shirt",
      category: "top",
      subcategory: "short-sleeve shirt",
      colours: {
        primary: "blue",
        secondary: ["white"],
        hex: ["#235c84", "#dbe4eb"],
      },
      pattern: "floral",
      material: "cotton",
      season: ["spring", "summer"],
      formality: "casual",
      description: "An adult men’s relaxed short-sleeve blue shirt with a white tropical leaf print.",
    },
  },
  {
    key: "v2-men-mens-henley",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/mens-henley.png",
    attributes: {
      name: "Two-tone Henley",
      category: "top",
      subcategory: "Henley",
      colours: {
        primary: "grey",
        secondary: ["black"],
        hex: ["#bdbdbd", "#202020"],
      },
      pattern: "colourblock",
      material: "cotton",
      season: ["spring", "autumn"],
      formality: "casual",
      description: "An adult men’s grey Henley with black raglan sleeves and a short button placket.",
    },
  },
  {
    key: "v2-men-mens-long-sleeve",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/mens-long-sleeve.png",
    attributes: {
      name: "Navy long-sleeve tee",
      category: "top",
      subcategory: "long-sleeve T-shirt",
      colours: {
        primary: "navy",
        secondary: [],
        hex: ["#3f5577"],
      },
      pattern: "solid",
      material: "cotton",
      season: ["spring", "autumn", "winter"],
      formality: "casual",
      description: "An adult men’s fitted navy long-sleeve crew-neck T-shirt.",
    },
  },
  {
    key: "v2-men-mens-cotton-jacket",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/mens-cotton-jacket.png",
    attributes: {
      name: "Sand field jacket",
      category: "outerwear",
      subcategory: "field jacket",
      colours: {
        primary: "beige",
        secondary: [],
        hex: ["#b3a08b"],
      },
      pattern: "solid",
      material: "cotton",
      season: ["spring", "autumn"],
      formality: "smart-casual",
      description: "An adult men’s sand-coloured field jacket with stand collar and front pockets.",
    },
  },
  {
    key: "v2-men-colourblock-trainers",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/colourblock-trainers.webp",
    attributes: {
      name: "Colourblock trainers",
      category: "shoes",
      subcategory: "trainers",
      colours: {
        primary: "blue",
        secondary: ["yellow", "white", "red"],
        hex: ["#19769c", "#eee166", "#f6f3e6"],
      },
      pattern: "colourblock",
      material: "mixed",
      season: ["spring", "summer", "autumn"],
      formality: "casual",
      description: "Adult men’s blue, yellow and cream low-top trainers with a red accent.",
    },
  },
  {
    key: "v2-men-white-red-trainers",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/white-red-trainers.webp",
    attributes: {
      name: "White and red trainers",
      category: "shoes",
      subcategory: "trainers",
      colours: {
        primary: "white",
        secondary: ["red"],
        hex: ["#efefeb", "#ad2534"],
      },
      pattern: "colourblock",
      material: "synthetic",
      season: ["spring", "summer", "autumn"],
      formality: "casual",
      description: "Adult men’s white low-top trainers with bold red panels and white laces.",
    },
  },
  {
    key: "v2-women-black-evening-gown",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/black-evening-gown.webp",
    attributes: {
      name: "Floral evening gown",
      category: "dress",
      subcategory: "maxi dress",
      colours: {
        primary: "black",
        secondary: ["pink", "blue", "green"],
        hex: ["#1b1b1b", "#c27791", "#638fbb"],
      },
      pattern: "floral",
      material: "polyester",
      season: ["spring", "summer"],
      formality: "formal",
      description: "An adult women’s floor-length black gown with colourful flowers and short sleeves.",
    },
  },
  {
    key: "v2-women-womens-leather-jacket",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/womens-leather-jacket.png",
    attributes: {
      name: "Black biker jacket",
      category: "outerwear",
      subcategory: "biker jacket",
      colours: {
        primary: "black",
        secondary: [],
        hex: ["#252525"],
      },
      pattern: "solid",
      material: "faux leather",
      season: ["spring", "autumn", "winter"],
      formality: "casual",
      description: "An adult women’s fitted black faux-leather jacket with a hood and zipped pockets.",
    },
  },
  {
    key: "v2-women-womens-blouse",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/womens-blouse.png",
    attributes: {
      name: "White draped top",
      category: "top",
      subcategory: "blouse",
      colours: {
        primary: "white",
        secondary: [],
        hex: ["#efefef"],
      },
      pattern: "solid",
      material: "viscose blend",
      season: ["spring", "summer"],
      formality: "smart-casual",
      description: "An adult women’s white short-sleeve top with a wide neckline and draped waist.",
    },
  },
  {
    key: "v2-women-womens-sport-top",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/womens-sport-top.png",
    attributes: {
      name: "Red V-neck tee",
      category: "top",
      subcategory: "T-shirt",
      colours: {
        primary: "red",
        secondary: [],
        hex: ["#c31e39"],
      },
      pattern: "solid",
      material: "polyester",
      season: ["spring", "summer"],
      formality: "casual",
      description: "An adult women’s red V-neck short-sleeve sports T-shirt.",
    },
  },
  {
    key: "v2-women-black-heeled-sandals",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/black-heeled-sandals.webp",
    attributes: {
      name: "Black heeled sandals",
      category: "shoes",
      subcategory: "heeled sandals",
      colours: {
        primary: "black",
        secondary: [],
        hex: ["#252525"],
      },
      pattern: "solid",
      material: "leather",
      season: ["spring", "summer"],
      formality: "smart-casual",
      description: "Adult women’s black open-toe heeled sandals with wide front and ankle straps.",
    },
  },
  {
    key: "v2-women-white-red-trainers",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/white-red-trainers.webp",
    attributes: {
      name: "White and red trainers",
      category: "shoes",
      subcategory: "trainers",
      colours: {
        primary: "white",
        secondary: ["red"],
        hex: ["#efefeb", "#ad2534"],
      },
      pattern: "colourblock",
      material: "synthetic",
      season: ["spring", "summer", "autumn"],
      formality: "casual",
      description: "Adult women’s white low-top trainers with bold red panels and white laces.",
    },
  },
  {
    key: "v2-women-brown-leather-bag",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/brown-leather-bag.webp",
    attributes: {
      name: "Brown shoulder bag",
      category: "bag",
      subcategory: "shoulder bag",
      colours: {
        primary: "brown",
        secondary: [],
        hex: ["#895030"],
      },
      pattern: "solid",
      material: "leather",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "smart-casual",
      description: "An adult women’s brown leather shoulder bag with two handles and gold-tone hardware.",
    },
  },
  {
    key: "v2-men-blue-jeans",
    wardrobe: "men",
    imagePath: "/demo-wardrobe/blue-jeans.png",
    attributes: {
      name: "Straight-leg blue jeans",
      category: "bottom",
      subcategory: "jeans",
      colours: {
        primary: "blue",
        secondary: [],
        hex: ["#527db2"],
      },
      pattern: "solid",
      material: "denim",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "casual",
      description: "Adult straight-leg blue denim jeans with classic five-pocket styling.",
    },
  },
  {
    key: "v2-women-blue-jeans",
    wardrobe: "women",
    imagePath: "/demo-wardrobe/blue-jeans.png",
    attributes: {
      name: "Straight-leg blue jeans",
      category: "bottom",
      subcategory: "jeans",
      colours: {
        primary: "blue",
        secondary: [],
        hex: ["#527db2"],
      },
      pattern: "solid",
      material: "denim",
      season: ["spring", "summer", "autumn", "winter"],
      formality: "casual",
      description: "Adult straight-leg blue denim jeans with classic five-pocket styling.",
    },
  },
];
