import type { Id } from "@convex/_generated/dataModel";

/** Every internal link goes through here so a route rename is one change. */
export const routes = {
  home: "/",
  signIn: "/sign-in",
  signUp: "/sign-up",
  onboarding: "/onboarding",
  add: "/add",
  gridDemo: "/grid-demo",
  wardrobe: "/wardrobe",
  item: (itemId: Id<"items"> | string) => `/wardrobe/${itemId}`,
  outfits: "/outfits",
  newOutfit: "/outfits/new",
  outfit: (outfitId: Id<"outfits"> | string) => `/outfits/${outfitId}`,
  lookbook: "/lookbook",
  shop: "/shop",
  services: "/services",
  service: (id: string) => `/services/${id}`,
  share: (token: string) => `/share/${token}`,
  billing: "/billing",
  settings: "/settings",
  admin: "/admin",
  adminSignIn: "/admin/sign-in",
  stylist: "/stylist",
  thread: (id: string) => `/stylist/${id}`,
  cart: "/cart",
  checkout: "/checkout",
  checkoutComplete: "/checkout/complete",
  orders: "/orders",
  order: (orderId: string) => `/orders/${orderId}`,
  store: (slug: string) => `/store/${slug}`,
  storeProduct: (slug: string, productSlug: string) => `/store/${slug}/${productSlug}`,
  vendor: "/vendor",
  vendorSignIn: "/vendor/sign-in",
  vendorSignUp: "/vendor/sign-up",
  vendorRegister: "/vendor/register",
  vendorProducts: "/vendor/products",
  vendorNewProduct: "/vendor/products/new",
  vendorImport: "/vendor/products/import",
  vendorProduct: (productId: Id<"products"> | string) => `/vendor/products/${productId}`,
  vendorDiscounts: "/vendor/discounts",
  vendorCollections: "/vendor/collections",
  vendorCategories: "/vendor/categories",
  vendorBrands: "/vendor/brands",
  vendorVariants: "/vendor/variants",
  vendorOrders: "/vendor/orders",
  vendorOrder: (id: string) => `/vendor/orders/${id}`,
  vendorPayouts: "/vendor/payouts",
  vendorSettings: "/vendor/settings",
  vendorBilling: "/vendor/settings/billing",
  adminVendors: "/admin/vendors",
} as const;
